### PR TITLE
Update readme to match usage from npmjs.com

### PR DESCRIPTION
**Pull request by amazingrando**
## What this PR does

This PR updates the usage instructions found in the [README](https://github.com/imagemin/imagemin-cli/blob/master/readme.md) to match the correct ones listed at https://www.npmjs.com/package/imagemin-cli.

## How to review this PR

- [ ] Run `imagemin images/* --out-dir=build` from the repo's instructions and see that it fails.
- [ ] Run `imagemin <file> <directory>` from the npmjs.com instructions and see that it works.

### CODE REVIEW

**Comment by amazingrando** [comment]
Also, thank you for writing and maintaining this package. I've found it quite useful!

**Comment by sindresorhus** [comment]
The readme here represents the current master. The readme on npm represents the latest version.

**Comment by sindresorhus** [comment]
@kevva Time to do a new major release?

**Comment by kevva** [comment]
@sindresorhus, yup. Haven't had time to take a deeper look into plugin options but we can add them later on instead.

**Pull request closed without merging**
