### PR TITLE
Fix/npm resolve path

### PR DESCRIPTION
**Pull request by tomchentw**
**What is the current behavior?**

When install `imagemin-cli@3.0.0` in the same repo, it has `get-stdin` as a shared dependency but with different versions. One is `@4.0.1` and one is `@5.0.1`.

However, due to the nature of [imagemin-cli][imagemin-cli], when it was run it'll use the `get-stdin@4.0.1` instead of its dependent one `get-stdin@5.0.1` due to **the node_modules structure**. See below for the result of `yarn list --pattern get-stdin`.

```sh
yarn add react-scripts@1.0.14
yarn add imagemin-cli@3.0.0
yarn list --pattern get-stdin
# --- And you should see this: ---
# yarn list v1.3.2
# ├─ get-stdin@4.0.1
# └─ imagemin-cli@3.0.0
#    └─ get-stdin@5.0.1
# ✨  Done in 0.74s.
# ---
# yarn why get-stdin
# info Has been hoisted to "get-stdin"
# info Reasons this module exists
#    - "imagemin-cli#meow#redent#strip-indent" depends on it
#    - "imagemin-cli#imagemin-gifsicle#gifsicle#logalot#squeak#lpad-align" depends on it
```

**What is the expected behavior?**

The `imagemin-cli` should use its owned dependency of `get-stdin`.

**Note**

At first, I suspect this might be an issue of `yarn` so I raise an issue [there][there]. However, they said it should be fixed in `imagemin-cli`. Let me know if you have further questions.

[imagemin-cli]: https://github.com/imagemin/imagemin-cli/blob/v3.0.0/cli.js
[there]: https://github.com/yarnpkg/yarn/issues/4897

### CODE REVIEW

**Comment by tomchentw** [comment]
There're some styling issues in the original code failing the CI. Should I fix them as well?

screen shot 2017-11-14 at 10 36 59 am

**Comment by shinnn** [comment]
> it has `get-stdin` as a shared dependency but with different versions. One is `@4.0.1` and one is `@5.0.1`.

That's how Node.js modules work. Availability of having different versions of the same module in a single project is one of the advantages of Node.js in comparison to others, for example Ruby gems.

----------

I don't understand what Burak said. The location of imagemin CLI entry point is totally nothing to do with this question.

**Comment by tomchentw** [comment]
@shinnn could you please try my example repo with `yarn`?
https://github.com/tomchentw/yarn-dependencies-versions

After installation, the `imagemin` CLI is
`node_modules/.bin/imagemin-cli` 
Which it requires, `get-stdin` is
`node_modules/get-stdin/` but not the correct one:`node_modules/imagemin-cli/node_modules/.get-stdin/` .

Applying my fix will forcing the node to resolve  `get-stdin` from this location:
`node_modules/imagemin-cli/`.
Which correctly resolves to `node_modules/imagemin-cli/node_modules/.get-stdin/`

**Comment by tomchentw** [comment]
> That's how Node.js modules work. Availability of having different versions of the same module in a single project is one of the advantages of Node.js in comparison to others, for example Ruby gems.

I totally understand that node.js module can work this way. The problem is 
`imagemin-cli` is requiring the **wrong** version of `get-stdin`  (`4.0.1` as opposed to `5.0.1` in its package.json)

**Comment by tomchentw** [comment]
@shinnn My apologies. When I try it again today there's no such issue :( it's weird but it seems not an issue of `imagemin-cli` nor `yarn`. Thanks for the help.

**Comment by shinnn** [comment]
@tomchentw No problem. Glad to hear that it worked.

**Pull request closed without merging**
