### PR TITLE
Add plugin options handling

### PR DESCRIPTION
**Pull request by antongolub**
Hi there.

I'd like to add optional plugin configuration. There  are a couple of solutions:
1) options as JSON (this PR)
```
--options={"plugins": [["pngquant", {"quality": [0.2, 0.5]}]]}
```
2) options as properties
```
--plugin.webp.quality=95
--plugin.pngquant.quality.0=0.2 --plugin.pngquant.quality.1=0.5
```

Which looks better?

### CODE REVIEW

**Comment by sindresorhus** [comment]
Definitely `2`.

**Comment by antongolub** [comment]
A useful side effect has appeared: now each plugin is loaded once.

Вefore:
```
imagemin --plugin=pngquant --plugin=pngquant --plugin=pngquant
↓
{
 ...,
 plugins: [
   require(`imagemin-pngquant`)(),
   require(`imagemin-pngquant`)(),
   require(`imagemin-pngquant`)()
 ]
}
```

After:
```
imagemin --plugin.pngquant.quality={0.1,0.2} --plugin=pngquant
↓
{
 ...,
 plugins: [
   require(`imagemin-pngquant`)({quality: [0.1, 0.2]})
 ]
}
```

**Comment by antongolub** [comment]
@sindresorhus, any objections / suggestions?

**Comment by antongolub** [comment]
@sindresorhus, is this good enough to be merged someday?

**Comment by antongolub** [comment]
@1000ch, @kevva , could anybody review this PR?

**Comment by HandsomeMedia** [comment]
Eagerly awaiting this merge 🙏

**Comment by sindresorhus** [comment]
Thanks, @antongolub 👍

**Pull request merged**
