### PR TITLE
Add overwrite option that replace the original file with a minified version.

### PR DESCRIPTION
**Pull request by larrabee**
Hello. This option is very useful for batch processing files.
Example 1:  
```
user@pc » ll fixtures/    
-rw-r--r-- 1 user user 77K мар 29 18:36 test.gif
-rw-r--r-- 1 user user 50K мар 29 18:36 test.jpg
-rw-r--r-- 1 user user 71K мар 29 18:36 test.png
-rw-r--r-- 1 user user 25K мар 29 18:36 test.svg
user@pc » node cli.js --overwrite fixtures/test.gif fixtures/test.svg fixtures/test.png fixtures/test.jpg 
user@pc » ll fixtures/                                                                                   
-rw-r--r-- 1 user user 77K мар 29 19:22 test.gif
-rw-r--r-- 1 user user 46K мар 29 19:22 test.jpg
-rw-r--r-- 1 user user 61K мар 29 19:22 test.png
-rw-r--r-- 1 user user 21K мар 29 19:22 test.svg
```
Example 2:  
```
user@pc » node cli.js --overwrite fixtures/*
```
Example 3:  
```
user@pc » find fixtures/ -name 'test.*' |xargs node cli.js --overwrite
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
This should be added to [`imagemin`](https://github.com/imagemin/imagemin) first and then used here.

**Comment by larrabee** [comment]
My code not require any changes in imagemin.

**Comment by sindresorhus** [comment]
I'm saying you've implemented it in the wrong place. And `overwrite` option can be useful for API consumers of Imagemin too, not just the CLI users. So if you want this, it needs to be implemented in `imagemin` as an `overwrite` option and then change this pull request to use that option.

**Comment by ceesvanegmond** [comment]
@sindresorhus @larrabee Would be quit usefull!

**Comment by sindresorhus** [comment]
Closing this for lack of activity. PR welcome on the `imagemin` repo.

**Pull request closed without merging**
