### PR TITLE
Chore/tweaks

### PR DESCRIPTION
**Pull request by 1000ch**
- Bump dependencies to align with the Node.js 10
- Fix lint issues

### CODE REVIEW

**Comment by 1000ch** [comment]
Does the [`isMultiple` option of `meow`](https://github.com/sindresorhus/meow#flags) return array always? then arrify might be omitted, but it seems to be not always.

**Comment by stephenwade** [comment]
@1000ch The `isMultiple` option returns an array for simple options, but it sometimes returns just an object for complex options. I think we need to keep `arrify`.

```diff
@@ -47,6 +47,9 @@ const cli = meow(`

 });

+console.log(cli.flags);
+process.exit(0);
+
 const requirePlugins = plugins => plugins.map(([plugin, options]) => {
        try {
                return require(`imagemin-${plugin}`)(options);
```

```
stephen@mbp:~/git/imagemin-cli$ ./cli.js -p a
{ plugin: [ 'a' ] }
stephen@mbp:~/git/imagemin-cli$ ./cli.js --plugin.pngquant.dithering=1
{ plugin: { pngquant: { dithering: 1 } } }
```

**Comment by stephenwade** [comment]
Also, I just noticed this while testing: the new version of `meow` requires the input to come before the options.

These changes need to be applied to the usage examples:

```diff
diff --git a/cli.js b/cli.js
index 41b7456..620127d 100755
--- a/cli.js
+++ b/cli.js
@@ -23,9 +23,9 @@ const cli = meow(`
 	  $ imagemin images/* --out-dir=build
 	  $ imagemin foo.png > foo-optimized.png
 	  $ cat foo.png | imagemin > foo-optimized.png
-	  $ imagemin --plugin=pngquant foo.png > foo-optimized.png
-	  $ imagemin --plugin.pngquant.quality={0.1,0.2} foo.png > foo-optimized.png
-	  $ imagemin --plugin.webp.quality=95 --plugin.webp.preset=icon foo.png > foo-icon.webp
+	  $ imagemin foo.png --plugin=pngquant > foo-optimized.png
+	  $ imagemin foo.png --plugin.pngquant.quality={0.1,0.2} > foo-optimized.png
+	  $ imagemin foo.png --plugin.webp.quality=95 --plugin.webp.preset=icon > foo-icon.webp
 `, {
 	flags: {
 		plugin: {
diff --git a/readme.md b/readme.md
index 58d3b02..9e5de47 100644
--- a/readme.md
+++ b/readme.md
@@ -44,9 +44,9 @@ $ imagemin --help
     $ imagemin images/* --out-dir=build
     $ imagemin foo.png > foo-optimized.png
     $ cat foo.png | imagemin > foo-optimized.png
-    $ imagemin --plugin=pngquant foo.png > foo-optimized.png
-    $ imagemin --plugin.pngquant.quality={0.1,0.2} foo.png > foo-optimized.png
-    $ imagemin --plugin.webp.quality=95 --plugin.webp.preset=icon foo.png > foo-icon.webp
+    $ imagemin foo.png --plugin=pngquant > foo-optimized.png
+    $ imagemin foo.png --plugin.pngquant.quality={0.1,0.2} > foo-optimized.png
+    $ imagemin foo.png --plugin.webp.quality=95 --plugin.webp.preset=icon > foo-icon.webp
 `​`​`
```

**Comment by 1000ch** [comment]
> the new version of meow requires the input to come before the options.

Right. But is this intentional behavior? 👀 it seems not to be mentioned on README.

Anyway, I'll update them.

**Pull request merged**
